# Generated by Django 4.2.1 on 2024-06-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedGrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(blank=True, max_length=128, null=True)),
                ('set', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('distribution_status', models.CharField(blank=True, max_length=128, null=True)),
                ('client_status', models.CharField(blank=True, max_length=128, null=True)),
                ('income', models.CharField(blank=True, max_length=128, null=True)),
                ('member_status', models.CharField(blank=True, max_length=128, null=True)),
                ('duplicate_name', models.CharField(blank=True, max_length=128, null=True)),
                ('verified_barangay', models.CharField(blank=True, max_length=128, null=True)),
                ('physical_cc_presented', models.CharField(blank=True, max_length=128, null=True)),
                ('eligible', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'validated_grants',
                'managed': True,
            },
        ),
    ]
