# Generated by Django 4.2.1 on 2024-06-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_validatedgrants'),
    ]

    operations = [
        migrations.CreateModel(
            name='GranteeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=128, null=True)),
                ('province', models.CharField(blank=True, max_length=128, null=True)),
                ('municipality', models.CharField(blank=True, max_length=128, null=True)),
                ('barangay', models.CharField(blank=True, max_length=128, null=True)),
                ('purok', models.CharField(blank=True, max_length=128, null=True)),
                ('address', models.CharField(blank=True, max_length=128, null=True)),
                ('hh_id', models.CharField(blank=True, max_length=128, null=True)),
                ('entryid', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('extension_name', models.CharField(blank=True, max_length=128, null=True)),
                ('birthday', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.CharField(blank=True, max_length=128, null=True)),
                ('client_status', models.CharField(blank=True, max_length=128, null=True)),
                ('member_status', models.CharField(blank=True, max_length=128, null=True)),
                ('registration_status', models.CharField(blank=True, max_length=128, null=True)),
                ('sex', models.CharField(blank=True, max_length=128, null=True)),
                ('relationship_to_hh_head', models.CharField(blank=True, max_length=128, null=True)),
                ('ipaffiliation', models.CharField(blank=True, max_length=128, null=True)),
                ('hh_set', models.CharField(blank=True, max_length=128, null=True)),
                ('group', models.CharField(blank=True, max_length=128, null=True)),
                ('mothers_maiden', models.CharField(blank=True, max_length=128, null=True)),
                ('date_of_enumeration', models.CharField(blank=True, max_length=128, null=True)),
                ('lbp_account_number', models.CharField(blank=True, max_length=128, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=128, null=True)),
                ('date_tagged_hhstatus', models.CharField(blank=True, max_length=128, null=True)),
                ('tagged_by', models.CharField(blank=True, max_length=128, null=True)),
                ('date_registered', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'grantee_list',
                'managed': True,
            },
        ),
    ]
