# Generated by Django 4.2.1 on 2024-06-13 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_granteelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatedgrants',
            name='barangay',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='cash_card_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='date_of_card_release_actual',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='date_of_card_released',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='extension_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='id_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='municipality',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='overall_remarks',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='province',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='sex',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='type_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='where_the_cash_card_released',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='validatedgrants',
            name='who_released_cash_card',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
