# Generated by Django 4.2.1 on 2024-06-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_validatedgrants_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatedgrants',
            name='eligible',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
